export const MLB: string[] = [
  'Houston Astros',
  'New York Yankees',
  'Minnesota Twins',
  'Boston Red Sox',
  'Cleveland Indians',
  'Baltimore Orioles',
  'Tampa Bay Rays',
  'Los Angeles Angels',
  'Texas Rangers',
  'Toronto Blue Jays',
  'Chicago White Sox',
  'Detroit Tigers',
  'Seattle Marines',
  'Kansas City Royals',
  'Oakland Athletics',
  'Washington Nationals',
  'Los Angeles Dogers',
  'Milwaukee Brewers',
  'Colorado Rockies',
  'Arizona Diamondbacks',
  'Chicago Cubs',
  'St. Louis Cardinals',
  'Cincinnati Reds',
  'New York Mets',
  'Pittsburgh Pirates',
  'Atlanta Braves',
  'San Francisco Giants',
  'Miami Marlins',
  'San Diego Padres',
  'Philadelphia Phillies'
]
